### ISSUE TITLE
service package discrepancy between RH6 and RH7

### ISSUE THREAD

**Issue by brettswift** [rnelson0/puppet-domain_join#27]
After rebasing the RH6 branch (#20)  we found an issue.   The yum package `samba-common-tools` doesn't seem to be available to us, or at least not in the repo that we were working with.

A good solution might be to have a recommended package list for both RH6 and 7.  I'm not sure if allowing these packages to be injected would be useful or not  - in this case we're looking to remove a package, not add one.

@rnelson0 does this sound like a good approach? 

I'm off for a couple weeks - the PR might come from someone else at work, or I could help when I'm back.

**Comment by rnelson0** [comment]
It sounds like a reasonable approach to me!

**Comment by chichimedina** [comment]
Hi Rob, I'm working with brettswift on this module. As he mentioned, there's an issue that shows up when installing 'samba-common-tools' package which is only available for RHEL7. I added a couple of 'if' to solve it.

   Please take a look at PR #31 

   Thanks.

**Comment by brettswift** [comment]
@rnelson0  thanks for merging the PR in.   

Just curious what your availability is to get a new release out the door.  I assume you need to schedule some time to test etc.    If you have an idea it'd be good to know! 

We can close this ticket now or when it's released, up to you.

**Comment by rnelson0** [comment]
I'm not in a good position to do testing for a while, but I think the tests should protect us. Unless you're able to test against HEAD and let me know shortly, I can do a new release tonight or tomorrow morning.

**Comment by rnelson0** [comment]
Released v0.5.1 today.
