### ISSUE TITLE
Invalid: Module does not Work with CentOs/RedHat 6.9 as described (issue is with unrelated realmd module)

### ISSUE THREAD

**Issue by josefprado** [rnelson0/puppet-domain_join#33]
When trying to join CentOs/RedHat 6.9 in the domain, this is the issue we are facing:

"Execution of '/usr/bin/yum -d 0 -e 0 -y install realmd' returned 1: Error: Nothing to do"

```
err | Puppet | Execution of '/usr/bin/yum -d 0 -e 0 -y install realmd' returned 1: Error: Nothing to do
err | /Stage[main]/Realmd::Install/Package[realmd]/ensure | change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install realmd' returned 1: Error: Nothing to do
err | Puppet | Execution of '/usr/bin/yum -d 0 -e 0 -y install samba-common-tools' returned 1: Error: Nothing to do
err | /Stage[main]/Realmd::Install/Package[samba-common-tools]/ensure | change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install samba-common-tools' returned 1: Error: Nothing to do
```

Basicaly, it just dont work in version 6.

**Comment by rnelson0** [comment]
Can you provide the output of `yum repolist; yum search realmd`?

**Comment by josefprado** [comment]
First of all, thanks for the fast response!!!

Sure, here it is:

`[root@server ~]# yum repolist; yum search realmd
Loaded plugins: rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
repo id                                                                                              repo name                                                                                                 status
server
![inkedpasted image at 2017_10_27 12_56 pm_li](https://user-images.githubusercontent.com/3974514/32110583-9b162ee2-bb16-11e7-9de4-0044b380f939.jpg)
-extras                                                                                         server-EXTRAS-LATEST                                                                                           29
centos6                                                                                              centos6_x86_64                                                                                             6,706
epel6x                                                                                               epel6_x86_64                                                                                              12,808
ocs-inventory_el6                                                                                    ocs-inventory_el6                                                                                              8
puppet-el6                                                                                           puppet_labs_el6_x86_64                                                                                       130
spacewalkel6                                                                                         spacewalk-el6_x86_64                                                                                         130
zabbix                                                                                               Zabbix                                                                                                        55
zabbix-el6                                                                                           zabbix_el6_x86_64                                                                                             57
repolist: 19,923
Loaded plugins: rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
================================================================================================== Matched: realmd ==================================================================================================
adcli.x86_64 : Active Directory enrollment`

As far as I know, there is no realmd for RedHat/CentOs 6, am I wrong?

**Comment by josefprado** [comment]
![inkedpasted image at 2017_10_27 12_56 pm_li](https://user-images.githubusercontent.com/3974514/32110628-bc4880ce-bb16-11e7-8465-3a18fc3d18e4.jpg)

**Comment by rnelson0** [comment]
@josefprado it looks from the output of the puppet run that you have a module realmd that is trying to install that package, and that’s not on the list of packages this module installs. If you remove that you’ll probably be okay.

Also, it looks like RHEL packages realmd in the package adcli. See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/windows_integration_guide/realmd-prepreqs as that may be a better fit for some users. This module is the most bare bones implementation possible, and some may enjoy the additional features of adcli and other tools that are available in a more complete install. I don’t want to turn you off to this module, but I want to make sure it’s a net benefit for you.

Thanks!

**Comment by josefprado** [comment]
You are completeley right!! Can you please remove this thread? I dont want that an issue be displayed there, since its not your fault :)

**Comment by rnelson0** [comment]
I added a tag and updated the description. This may help someone else with the same problem, but it won’t be in the changelog anymore.
